FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
COPY frontend/docker-dist/standalone ./
COPY frontend/docker-dist/static ./.next/static
COPY frontend/docker-dist/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
